### ISSUE TITLE
DocumentNTF(NTF1,osr=8) shows blank plots

### ISSUE THREAD

**Issue by sumitkhalapure24** [ggventurini/python-deltasigma#66]
DocumentNTF(NTF1,osr=8) shows blank plots 
Errors are:
 plotPZ(ntf, 'b', 6, showlist=False) line 85, in plotPZ
    hold_status = plt.ishold()
 AttributeError: module 'pylab' has no attribute 'ishold'
Please suggest an alternative to get the plot in spyder windows

**Comment by lmsantana** [comment]
For me, it helped to suppress the line
`hold_status = plt.ishold()`
in every point of the source code they appear.

I am using spyder 3.3.3

**Comment by sumitkhalapure24** [comment]
Thanks lmsantana. The newer version of spyder has removed ishold, therefore it worked in spyder 3.3.3.
